CREATE TABLE BOOK (
NAME varchar (20),
AUTHOR varchar (20),
PUBLISHER varchar (20),
PRICE integer);
INSERT INTO BOOK VALUES
('JAVA','ROBERT','TATAMCGRAWL DILL',599);
INSERT INTO BOOK VALUES 
('DBMS','SILBERSCHILZ','ROYAL',450);
SELECT* FROM BOOK;
SELECT NAME FROM BOOK
WHERE PRICE>300;
DELETE FROM BOOK
WHERE PUBLISHER ='ROYAL';
SELECT * FROM BOOK;
ALTER TABLE BOOK ADD YEAR integer(4);
UPDATE BOOK SET YEAR=2012
WHERE NAME='JAVA';
SELECT * FROM BOOK;
SELECT AUTHOR FROM BOOK 
WHERE AUTHOR LIKE 'A%';
SELECT * FROM BOOK;